# Generated by Django 2.2 on 2020-08-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_messages', '0004_auto_20200818_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_messages.Message')),
                ('uploaded_file', models.FileField(upload_to='messages/%Y/%m/%D')),
            ],
            bases=('django_messages.message',),
        ),
    ]
