# Generated by Django 2.2 on 2020-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(default='slug', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
