# Generated by Django 2.2 on 2020-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/%D'),
        ),
    ]
