# Generated by Django 2.2.12 on 2020-09-13 00:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
