# Generated by Django 2.2.14 on 2020-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200913_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delete_once',
            field=models.BooleanField(default=False),
        ),
    ]
