# Generated by Django 2.2.14 on 2020-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_delete_once'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='delete_once',
            new_name='recipient_delete_once',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_delete_once',
            field=models.BooleanField(default=False),
        ),
    ]
