# Generated by Django 2.2 on 2020-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('S', 'Subscribed'), ('P', 'Pending'), ('U', 'Unsubscribed')], max_length=1)),
                ('subscribed_on', models.DateTimeField()),
            ],
        ),
    ]
