# Generated by Django 2.2 on 2020-08-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
