# Generated by Django 2.2.12 on 2020-08-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('address', models.CharField(default=None, max_length=60)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(max_length=60, null=None)),
                ('website', models.URLField(blank=True)),
                ('is_partner', models.BooleanField(default=False, verbose_name='Is a partner')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60)),
                ('last_name', models.CharField(default=None, max_length=60)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(max_length=60, null=None)),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Is a supplier')),
                ('is_donor', models.BooleanField(default=False, verbose_name='Is a donor')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Is subscribed to the newsletter')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
            },
        ),
    ]
