# Generated by Django 2.2 on 2020-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60, verbose_name='Prénom')),
                ('last_name', models.CharField(default=None, max_length=60, verbose_name='Nom')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(max_length=60, null=None, verbose_name='Téléphone')),
                ('company', models.CharField(max_length=60, verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
