# Generated by Django 2.2 on 2020-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('DONATOR', 'Donator'), ('SUPPLIER', 'Supplier')], default='DONATOR', max_length=10, verbose_name='Type de transfert'),
        ),
    ]
