# Generated by Django 2.2 on 2020-06-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_person_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_type',
        ),
        migrations.AddField(
            model_name='person',
            name='is_donor',
            field=models.BooleanField(default=False, verbose_name='Est un donateur'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Est un fournisseur'),
        ),
    ]
