# Generated by Django 2.2 on 2020-07-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200617_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='adresse',
            field=models.CharField(default=None, max_length=60, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Is a partner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=60, null=None, verbose_name='Phone number'),
        ),
    ]
