# Generated by Django 3.1.1 on 2020-10-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200922_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
    ]
