# Generated by Django 2.2 on 2020-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200724_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Individual', 'verbose_name_plural': 'Individuals'},
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=60, unique=True),
        ),
    ]
