# Generated by Django 3.1.1 on 2020-10-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_person_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_supplier',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
    ]
