# Generated by Django 2.2 on 2020-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200724_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AlterField(
            model_name='company',
            name='adresse',
            field=models.CharField(default=None, max_length=60, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Est un partenaire'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=60, null=None, verbose_name='Téléphone'),
        ),
    ]
