# Generated by Django 2.2 on 2020-07-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20200724_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adresse',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=60, null=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_donor',
            field=models.BooleanField(default=False, verbose_name='Is a donor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_follower',
            field=models.BooleanField(default=False, verbose_name='Is subscribed to the newsletter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Is a supplier'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=60, null=None),
        ),
    ]
