# Generated by Django 2.2 on 2020-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20200724_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='site_web',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
