# Generated by Django 2.2.12 on 2020-08-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20200815_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
    ]
