# Generated by Django 2.2.12 on 2020-08-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_remove_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=60, null=None),
            preserve_default=False,
        ),
    ]
