# Generated by Django 2.2.12 on 2020-08-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_person_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_subscribed',
            new_name='is_subscribed',
        ),
    ]
