# Generated by Django 2.2.12 on 2020-08-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_auto_20200815_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_subscsribed',
            new_name='is_subscribed',
        ),
    ]
