# Generated by Django 2.2.14 on 2020-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200915_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='yo'),
            preserve_default=False,
        ),
    ]
