# Generated by Django 2.2.14 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200919_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/post/default.svg', null=True, upload_to='blog/post/%Y/%m/%D'),
        ),
    ]
