# Generated by Django 2.2.14 on 2020-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200920_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/post/page.svg', upload_to='blog/post/%Y/%m/%D'),
        ),
    ]
