# Generated by Django 2.2.12 on 2020-08-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Starting date')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Termination date')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='slug', max_length=60, unique=True)),
                ('state', models.CharField(choices=[('TODO', 'TO DO'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('LATE', 'LATE'), ('DONE', 'DONE')], default='TODO', max_length=11, verbose_name='Statut')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Projet')),
                ('users', models.ManyToManyField(to='account.User')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('MemberMeeting', 'Meeting between members'), ('FundRainsing', 'Fund rainsing')], default='MemberMeeting', max_length=14)),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('time_started', models.DateTimeField(blank=True, verbose_name='Start of the event')),
                ('time_ended', models.DateTimeField(blank=True, verbose_name='End of the event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('users', models.ManyToManyField(blank=True, to='account.User')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
