# Generated by Django 2.2 on 2020-06-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('type', models.CharField(choices=[('MemberMeeting', 'Meeting between members'), ('FundRainsing', 'Fund rainsing')], default='MemberMeeting', max_length=11, verbose_name="Type d'évènement")),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name="URL de l'image")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('time_started', models.DateTimeField(blank=True, verbose_name="Début de l'évènement")),
                ('time_ended', models.DateTimeField(blank=True, verbose_name="Fin de l'évènement")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('users', models.ManyToManyField(blank=True, to='account.User')),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
                'ordering': ['-date_created'],
            },
        ),
    ]
