# Generated by Django 2.2 on 2020-08-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200819_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
