# Generated by Django 2.2 on 2020-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MemberMeeting', 'Meeting between members'), ('FundRainsing', 'Fund rainsing')], default='MemberMeeting', max_length=13, verbose_name="Type d'évènement"),
        ),
    ]
