# Generated by Django 2.2 on 2020-08-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200801_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_ended',
            field=models.DateTimeField(blank=True, verbose_name='End of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_started',
            field=models.DateTimeField(blank=True, verbose_name='Start of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MemberMeeting', 'Meeting between members'), ('FundRainsing', 'Fund rainsing')], default='MemberMeeting', max_length=13, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='Termination date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
