# Generated by Django 2.2 on 2020-09-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200909_0118'),
        ('project', '0004_auto_20200910_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_created_by', to='account.User'),
            preserve_default=False,
        ),
    ]
