# Generated by Django 2.2 on 2020-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200821_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MemberMeeting', 'Meeting between members'), ('FundRaising', 'Fund rainsing')], default='MemberMeeting', max_length=14),
        ),
    ]
