# Generated by Django 2.2 on 2020-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200807_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MemberMeeting', 'Meeting between members'), (
                'FundRainsing', 'Fund rainsing')], default='MemberMeeting', max_length=11, verbose_name="Type d'évènement"),
        ),
    ]
