# Generated by Django 2.2.14 on 2020-09-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200917_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
