# Generated by Django 2.2.14 on 2020-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('TODO', 'TO DO'), ('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('LATE', 'LATE'), ('DONE', 'DONE')], default='TODO', max_length=11, verbose_name='Statut'),
        ),
    ]
