# Generated by Django 2.2.14 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200919_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='account/user/avatar/page.svg', upload_to='project/event/%Y/%m/%D'),
            preserve_default=False,
        ),
    ]
