# Generated by Django 2.2.14 on 2020-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200920_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='project/project/event.svg', upload_to='project/event/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project/project/project.svg', upload_to='project/project/%Y/%m/%D'),
        ),
    ]
