# Generated by Django 2.2.14 on 2020-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200920_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='project/event/event.svg', upload_to='project/event/%Y/%m/%D'),
        ),
    ]
