# Generated by Django 2.2.12 on 2020-08-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200815_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='newsletter',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
