# Generated by Django 2.2 on 2020-06-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStock',
            new_name='ProductStockTransfert',
        ),
    ]
