# Generated by Django 2.2.14 on 2020-09-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocktransfert',
            name='transfert_type',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('DELIVERY', 'Delivery')], default='RECEPTION', max_length=10),
        ),
    ]
