# Generated by Django 2.2.14 on 2020-09-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200914_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstocktransfert',
            options={'ordering': ['-id'], 'verbose_name': 'Transfert de produits', 'verbose_name_plural': 'Transferts de produits'},
        ),
    ]
