# Generated by Django 2.2.14 on 2020-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200915_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktransfert',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
