# Generated by Django 2.2.14 on 2020-09-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
