# Generated by Django 2.2 on 2020-08-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstocktransfert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Product'),
        ),
        migrations.AlterField(
            model_name='productstocktransfert',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='productstocktransfert',
            name='transfert_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productstocktransfert',
            name='transfert_type',
            field=models.CharField(choices=[('RECEPTION', 'Réception'), ('RECEPTION', 'Livraison')], default='RECEPTION', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
