# Generated by Django 2.2 on 2020-08-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200810_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstocktransfert',
            old_name='transfert_date',
            new_name='date_created',
        ),
    ]
