# Generated by Django 2.2.12 on 2020-08-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200811_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstocktransfert',
            old_name='date_created',
            new_name='date_time_created',
        ),
    ]
