# Generated by Django 2.2.12 on 2020-08-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('project', '0001_initial'),
        ('contact', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransactionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=None, verbose_name='Quantité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Product', verbose_name='Produits')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Ligne de commandes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Donation', 'Donation'), ('Purchase', 'Purchase'), ('Sell', 'Sell')], default='Donation', max_length=10, verbose_name='Type de transfert')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Est valide')),
                ('person', models.ForeignKey(blank=True, null='NULL', on_delete=django.db.models.deletion.PROTECT, to='contact.Person', verbose_name='Personne')),
                ('products_transaction', models.ManyToManyField(blank=True, through='transaction.ProductTransactionLine', to='stock.Product', verbose_name='Liste de produits')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='Projet')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to='account.User', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_time_created'],
            },
        ),
        migrations.AddField(
            model_name='producttransactionline',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transaction.Transaction'),
        ),
    ]
