# Generated by Django 2.2 on 2020-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(blank=True, through='transaction.ProductTransactionLine', to='stock.Product', verbose_name='Liste de produits'),
        ),
    ]
