# Generated by Django 2.2 on 2020-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200615_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Purchase', 'Purchase'), ('Sell', 'Sell')], default='Donation', max_length=10, verbose_name='Type de transfert'),
        ),
    ]
