# Generated by Django 2.2 on 2020-07-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
