# Generated by Django 2.2 on 2020-09-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200911_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='with_paypal',
            field=models.BooleanField(default=False),
        ),
    ]
