# Generated by Django 2.2.12 on 2020-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200713_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time_created'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='products',
            new_name='products_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
    ]
