# Generated by Django 2.2 on 2020-09-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200821_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_time_created']},
        ),
        migrations.AlterField(
            model_name='producttransactionline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product'),
        ),
        migrations.AlterField(
            model_name='producttransactionline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
