# Generated by Django 3.1.1 on 2020-10-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_person_created_by'),
        ('transaction', '0005_auto_20201014_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.company'),
        ),
    ]
