# Generated by Django 2.2 on 2020-09-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20200905_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttransactionline',
            options={},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(blank=True, null='NULL', on_delete=django.db.models.deletion.PROTECT, to='contact.Person'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='products_transaction',
            field=models.ManyToManyField(blank=True, through='transaction.ProductTransactionLine', to='stock.Product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Purchase', 'Purchase'), ('Sell', 'Sell')], default='Donation', max_length=10),
        ),
    ]
