# Generated by Django 2.2 on 2020-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20200906_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Purchase', 'Purchase'), ('Sell', 'Sell')], max_length=10),
        ),
    ]
