# Generated by Django 2.2 on 2020-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='account/user/avatar/%Y/%m/%D'),
        ),
    ]
