# Generated by Django 2.2.14 on 2020-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200909_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='account/user/avatar/page.svg', null=True, upload_to='account/user/avatar/%Y/%m/%D'),
        ),
    ]
