# Generated by Django 2.2 on 2020-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='account/user/avatar/default.jpg', null=True, upload_to='account/user/avatar/%Y/%m/%D'),
        ),
    ]
