# Generated by Django 2.2.14 on 2020-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200920_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='account/user/avatar/default.svg', null=True, upload_to='account/user/avatar/%Y/%m/%D'),
        ),
    ]
