# Generated by Django 2.2 on 2020-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200721_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='account/user/avatar/default.svg', null=True, upload_to='account/user/avatar/%Y/%m/%D'),
        ),
    ]
